### ISSUE TITLE
dev_dev_index.json file is missing

### ISSUE THREAD

**Issue by hxc1008** [thunlp/DocRED#10]
Where should I get the dev_dev_index.json file to successfully run the evidence extraction script? It seems like the file is not generated by the gen_data.py script. Thanks!

**Comment by YeDeming** [comment]
It is generated by the test result of relation extraction, test.py. We make a pipeline progress, first to  generate relation fact triple, then the evidence.

**Comment by hxc1008** [comment]
But the only way to get the test result is to submit to codalab, right?

**Comment by YeDeming** [comment]
You can use test.py to  get the relation extraction result, then use the test_sp.py to get the supporting fact result.

**Comment by hxc1008** [comment]
But the dev_test.json has no labels? How should I get the "relation extraction" result?

**Comment by YeDeming** [comment]
Use train.py to train a RE model and use test.py to test on test set.

**Comment by hxc1008** [comment]
The problem is the test set, "dev_test.json" file, has no LABEL.

**Comment by YeDeming** [comment]
yep，you need use your trained model to predict the label. After that, submit to the codaLab for test.

**Comment by hxc1008** [comment]
So, same as the second comment I made, one has to submit to codalab to get the TEST RESULT. Is that right?

**Comment by YeDeming** [comment]
Yes, the label of test set is hidden.

**Comment by hxc1008** [comment]
Thanks
