### ISSUE TITLE
F1 error

### ISSUE THREAD

**Issue by oddmen** [thunlp/DocRED#11]
您好！
      我们在使用readme中该代码训练模型的时候，出现f1值一直为0的情况，当然这也导致了训练模型无法保存的问题。我们完整的验证了多次，都会出现这个问题，想请教一下是什么问题导致的。
`CUDA_VISIBLE_DEVICES=0 python3 train.py --model_name BiLSTM --save_name checkpoint_BiLSTM --train_prefix dev_train --test_prefix dev_dev`

`-----------------------------------------------------------------------------------------
| epoch 195 | step 15050 |  ms/b 11739.73 | train loss 0.000 | NA acc: 1.00 | not NA acc: 0.93  | tot acc: 1.00
| epoch 196 | step 15100 |  ms/b 5017.40 | train loss 0.000 | NA acc: 1.00 | not NA acc: 0.93  | tot acc: 1.00
| epoch 196 | step 15150 |  ms/b 5109.55 | train loss 0.000 | NA acc: 1.00 | not NA acc: 0.93  | tot acc: 1.00
| epoch 197 | step 15200 |  ms/b 4961.75 | train loss 0.000 | NA acc: 1.00 | not NA acc: 0.92  | tot acc: 1.00
| epoch 198 | step 15250 |  ms/b 5002.38 | train loss 0.000 | NA acc: 1.00 | not NA acc: 0.93  | tot acc: 1.00
| epoch 198 | step 15300 |  ms/b 4956.10 | train loss 0.000 | NA acc: 1.00 | not NA acc: 0.93  | tot acc: 1.00
| epoch 199 | step 15350 |  ms/b 5005.01 | train loss 0.000 | NA acc: 1.00 | not NA acc: 0.92  | tot acc: 1.00
| epoch 199 | step 15400 |  ms/b 5073.45 | train loss 0.000 | NA acc: 1.00 | not NA acc: 0.92  | tot acc: 1.00
-----------------------------------------------------------------------------------------
total_recall 12323
ALL   : Theta 1.0000 | F1 0.0000 | AUC 0.0000
Ignore ma_f1 0.0000 | input_theta 1.0000 test_result F1 0.0000 | AUC 0.0000
| epoch 199 | time: 347.25s
-----------------------------------------------------------------------------------------
Finish training
Best epoch = 0 | auc = 0.000000
Storing best result...`

**Comment by YeDeming** [comment]
We are trying to fix it.

**Comment by YeDeming** [comment]
我换了台机器也是正常的，抱歉暂时不太确定你这边为什么会出错

**Comment by YeDeming** [comment]
可能因为之前rel2id.json错误了，已在[TsinghuaCloud](https://cloud.tsinghua.edu.cn/d/99e1c0805eb64736af95/)中更新

**Comment by oddmen** [comment]
感觉您的回复。更新 rel2id.json后 F1有数值变化了，这个问题应该是被解决了。
