### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by UCAS2018** [thunlp/DocRED#12]
运行下面命令的时候报错：
CUDA_VISIBLE_DEVICES=0 python3 train.py --model_name BiLSTM --save_name checkpoint_BiLSTM --train_prefix dev_train --test_prefix dev_dev
-----------------------------------------------------------------------------------
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    con.train(model[args.model_name], args.save_name)
  File "/home/tanghengzhu/experiment/DocRED/code/config/Config.py", line 529, in train
    f1, auc, pr_x, pr_y = self.test(model, model_name)
  File "/home/tanghengzhu/experiment/DocRED/code/config/Config.py", line 629, in test
    test_result_ignore.append(((h_idx, t_idx, r) in label, float(predict_re[i,j,r]),  titles[i], self.id2rel[r], index, h_idx, t_idx, r))
KeyError: 1
------------------------------------------------------------------------------------
另外我还有个问题是程序中加载数据的时候没有将relation由string类型变成int类型

**Comment by YeDeming** [comment]
感谢你的反馈，rel2id.json的目标键值应该是数字而不是字符串，已在[TsinghuaCloud](https://cloud.tsinghua.edu.cn/d/99e1c0805eb64736af95/)中更新

**Comment by UCAS2018** [comment]
在运行test.py时，为什么得到F1和AUC全是0呢？

下面是我的运行命令：
CUDA_VISIBLE_DEVICES=0 python3 test.py --model_name BiLSTM --save_name checkpoint_BiLSTM --train_prefix dev_train --test_prefix dev_test --input_theta 0.3290

然后这是我得到的结果：
total_recall 0
ma_f10.0000 | input_theta 0.3290 test_result F1 0.0000 | AUC 0.0000
Ignore ma_f1 0.0000 | input_theta 1.0000 test_result F1 0.0000 | AUC 0.0000

**Comment by YeDeming** [comment]
感谢你的反馈，readme中--test_prefix应该为dev_dev这样测试的是验证集，有标注，测试集没有标注只会输出结果文件
CUDA_VISIBLE_DEVICES=0 python3 test.py --model_name BiLSTM --save_name checkpoint_BiLSTM --train_prefix dev_train --test_prefix dev_dev --input_theta 0.3290

**Comment by UCAS2018** [comment]
奥奥明白了，非常感谢！

**Comment by UCAS2018** [comment]
不好意西，还有个问题，测试集没有标注的话，那论文中测试集上的“Ign F1, Ign AUC, F1, AUC”这些指标是怎么得到的呢？是将测试集上的结果文件提交到Codalab就可以得到吗？
另外，我看了evaluation.py这份评测代码，只计算了F1值，所以提交到Codalab上的结果文件也只是评测F1值对吗？

**Comment by YeDeming** [comment]
是的，codalab上目前只评测了F1

**Comment by YeDeming** [comment]
codalab链接已更新，评测ignF1和F1
