### ISSUE TITLE
Relations

### ISSUE THREAD

**Issue by nayakt** [thunlp/DocRED#14]
Hi,

Can you please add the relation details (their wikidata Id, name and description) here ? Sometimes these details changes with the wikidata version. A simple json file will be very helpful. 

Regards
Tapas

**Comment by YeDeming** [comment]
Relation details is attached as Appendices A.3 in paper.

**Comment by thinkhoon** [comment]
> Relation details is attached as Appendices A.3 in paper.

why don't you trans the relation to well format json data and put it on clouddisk?
o(╥﹏╥)o
