### ISSUE TITLE
Evaluation script

### ISSUE THREAD

**Issue by hxc1008** [thunlp/DocRED#15]
Hi, I have a question about the test function, under Config.py file, line 631. When appending to test result array, you enumerate all the possible combinations of (h_idx, t_idx, r), and then you use it as the "correct", in line 665, to calculate the F1 score. But from my understanding, in this way, the "correct" variable is always the same, which is just the total number of "not NA relations" in the test file. Could you explain that a little bit?

**Comment by YeDeming** [comment]
Hi,
When (h_idx, t_idx, r) is a valid relational fact, correct will be add 1, as `(h_idx, t_idx, r) in label`.
We should choose a probability theta for remaining predicted relational facts for higher F1 scores.
