### ISSUE TITLE
How to use current evaluation script?

### ISSUE THREAD

**Issue by woshiyyya** [thunlp/DocRED#16]
Hi, I found you updated the evaluation script. But the directory structure is inconsistent with current train/test code. Can you describe how to use it?

**Comment by YeDeming** [comment]
Hi, 
"result.json"(your result file) is placed in input_dir/res/ 
"dev_dev.json"(the annotated data) is placed in input_dir/ref/
"train_annotated.json" and "train_distant.json" is placed in ../data/ for computed ignore scores.

**Comment by woshiyyya** [comment]
Thank you！

**Comment by ssppff** [comment]
> 嗨，
> “ result.json”（您的结果文件）放置在input_dir / res /中
> “ dev_dev.json”（带注释的数据）放置在input_dir / ref / 
> “ train_annotated.json”中，“ train_distant.json”放置在../data/用于计算的忽略分数。

Hello, I'd like to ask where the "input_dir" file is. I'm sorry I didn't find it. I hope you can help me.

**Comment by YeDeming** [comment]
you should create input_dir

**Comment by ssppff** [comment]
Thank you for your help. I want to ask which program "result. json" is the result of. I didn't see it in the description.

**Comment by YeDeming** [comment]
Here is the format: https://competitions.codalab.org/competitions/20717#learn_the_details-submission-format

**Comment by vhientran** [comment]
Hi @YeDeming ,

Sorry for disturbing you. However, I tried to submit the prediction file: result.zip to Codalab, but I cannot get the performance, with FAIL Submission. Here is the error:

Error:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmphyguXA/run/program/evaluate.py", line 78, in 
    tmp = json.load(open(submission_answer_file))
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmphyguXA/run/input/res/result.json'

Please help me to solve it. Thanks so much!

**Comment by YeDeming** [comment]
Hi, participantes need to compress the result file (result.json) into zip format (result.zip) for submission.

What is your Submission Fotmat?

**Comment by vhientran** [comment]
Hi @YeDeming ,

Now I can submit. Thank you!
