### ISSUE TITLE
Readability

### ISSUE THREAD

**Issue by WindChimeRan** [thunlp/DocRED#20]
May I ask you to add more comments to the code? It's a bit hard for me to guess the exact meaning of many variables.  

For example, what are h_mapping and t_mapping? 
https://github.com/thunlp/DocRED/blob/master/code/config/Config.py#L281-L289

Thank you for your contribution to opensource research!

**Comment by YeDeming** [comment]
Hi,
A head entity have len(hlist) mentions. [h['pos'][0], h['pos'][1]) is a mention's position in the document.  

h_mapping[i, j, h['pos'][0]:h['pos'][1]] = 1.0 / len(hlist) / (h['pos'][1] - h['pos'][0])

Each position of a mention shares the same coefficient.

**Comment by dawn2034** [comment]
What are max_length, coref_size, entity_type_size, sent_limit and dis_size?

I have many troubles when using your code on other dataset.

It's very grateful if you add some comments to the code. Thanks!

**Comment by YeDeming** [comment]
max_length means the upper limit of document length. sent_limit is used for the evidence sentence extraction.
coref_size, entity_type_size  and dis_size are the hidden size of each features described in Table 6 in our paper
