### ISSUE TITLE
missing words

### ISSUE THREAD

**Issue by sunilitggu** [thunlp/DocRED#21]
In some documents, it seems like words are missing e.g.  ['The', 'episode', 'is', 'noted', 'as', 'playing', 'homage', 'to', 'the', 'tradition', 'of', '"', 'trashy', 'science', 'fiction', 'horror', '"', 'vibe', 'in', 'the', 'Star', 'Trek', 'universe', 'as', 'portrayed', 'by', 'episodes', 'like', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', ',', '"', 'Dark', 'Page', '"', ',', '"', '"', ',', '"', '"', ',', '"', '"', 'or', '"', '"', '.']

Any comment on this?

**Comment by yaoyuanTHU** [comment]
It seems some of the special tokens are missing, possibly due to their special markers in raw text. Sorry for the missing words. We will try to fix this in our new release. Fortunately, it should not affect the training and evaluation on the dataset right now.
