### ISSUE TITLE
运行时间

### ISSUE THREAD

**Issue by wt123u** [thunlp/DocRED#22]
你好，想请问下用BiLSTM训练annotated数据集大概要多久呢？我在训练的时候发现cpu占用特别高，gpu利用率特别低，想知道这是什么原因呢，感谢分享。

**Comment by YeDeming** [comment]
因为程序预处理时间比较多所以cpu占用比较高，抱歉不太记得要训练多久了

**Comment by wt123u** [comment]
好的，非常感谢，我用BiLSTM训练，大概是一天多，26个小时好像是这样。
