### ISSUE TITLE
train_distance_data数据有问题吗？

### ISSUE THREAD

**Issue by yangxia605** [thunlp/DocRED#24]
![image](https://user-images.githubusercontent.com/21167278/66448314-b03e5080-ea83-11e9-9d69-373db978e952.png)
![image](https://user-images.githubusercontent.com/21167278/66448318-b3394100-ea83-11e9-95ee-2986fb7c2a0b.png)
执行 python3 gen_data.py --in_path ../data --out_path prepro_data 时报错。thanks！

**Comment by YeDeming** [comment]
我这边没有问题，你是下载的最新的吗，从TsinghuaCloud还是GoogleCloud

**Comment by yangxia605** [comment]
这一份是从TsinghuaCloud下载的，我又重新从GoogleCloud下载了一份，现在可以了。thanks!
