### ISSUE TITLE
Some of data don't have labels?

### ISSUE THREAD

**Issue by benbijituo** [thunlp/DocRED#28]
Some of data don't have labels.
![image](https://user-images.githubusercontent.com/45055255/68857663-3f432600-071e-11ea-99d5-e12d1d8aca05.png)
![image](https://user-images.githubusercontent.com/45055255/68857701-508c3280-071e-11ea-9d82-6ed41cc4e224.png)

**Comment by benbijituo** [comment]
If the labels of some documents are empty, does it mean that there aren't any relational facts in these documents?

**Comment by YeDeming** [comment]
Sorry for the late reply. Yes, it mean that there aren't any relational facts in these documents.
