### ISSUE TITLE
data idx of head entity in vertexSet

### ISSUE THREAD

**Issue by cj555** [thunlp/DocRED#3]
Hi, thunlp

Could you explain what **idx of head entity in vertexSet** in the label field refers to? 
The vertexSet in the real data seems have nested layers.
Thanks.

Data Format:
{
  'title',
  'sents':     [
                  [word in sent 0],
                  [word in sent 1]
               ]
  'vertexSet': [
                  [
                    { 'name': mention_name, 
                      'sent_id': mention in which sentence, 
                      'pos': postion of mention in a sentence, 
                      'type': NER_type}
                    {anthor mention}
                  ], 
                  [anthoer entity]
                ]
  'labels':   [
                {
                  'h': **idx of head entity in vertexSet**,
                  't': idx of tail entity in vertexSet,
                  'r': relation,
                  'evidence': evidence sentences' id
                }
              ]
}

{
    "labels": [
        {
            "evidence": [
                0
            ],
            "h": 6,
            "r": "P131",
            "t": 7
        },
        {
            "evidence": [
                0,
                2
            ],
            "h": 6,
            "r": "P131",
            "t": 10
        },
        {
            "evidence": [
                0
            ],
            "h": 6,
            "r": "P17",
            "t": 4
        },
        {
            "evidence": [],
            "h": 7,
            "r": "P131",
            "t": 10
        },
        {
            "evidence": [
                0
            ],
            "h": 7,
            "r": "P17",
            "t": 4
        },
        {
            "evidence": [
                0
            ],
            "h": 7,
            "r": "P206",
            "t": 5
        },
        {
            "evidence": [
                0,
                2
            ],
            "h": 10,
            "r": "P17",
            "t": 4
        },
        {
            "evidence": [
                2,
                3
            ],
            "h": 10,
            "r": "P150",
            "t": 11
        },
        {
            "evidence": [
                0,
                3
            ],
            "h": 13,
            "r": "P17",
            "t": 4
        },
        {
            "evidence": [
                0,
                1,
                2
            ],
            "h": 2,
            "r": "P131",
            "t": 10
        },
        {
            "evidence": [
                0
            ],
            "h": 2,
            "r": "P17",
            "t": 4
        },
        {
            "evidence": [
                0
            ],
            "h": 2,
            "r": "P206",
            "t": 5
        },
        {
            "evidence": [
                0,
                1,
                2
            ],
            "h": 3,
            "r": "P131",
            "t": 10
        },
        {
            "evidence": [
                0
            ],
            "h": 3,
            "r": "P17",
            "t": 4
        },
        {
            "evidence": [
                0
            ],
            "h": 3,
            "r": "P206",
            "t": 5
        },
        {
            "evidence": [
                0,
                2
            ],
            "h": 0,
            "r": "P131",
            "t": 10
        },
        {
            "evidence": [
                0
            ],
            "h": 0,
            "r": "P527",
            "t": 2
        },
        {
            "evidence": [
                0
            ],
            "h": 0,
            "r": "P527",
            "t": 3
        },
        {
            "evidence": [
                0
            ],
            "h": 0,
            "r": "P17",
            "t": 4
        },
        {
            "evidence": [
                0
            ],
            "h": 5,
            "r": "P17",
            "t": 4
        },
        {
            "evidence": [
                2,
                3
            ],
            "h": 11,
            "r": "P131",
            "t": 10
        },
        {
            "evidence": [
                0,
                3
            ],
            "h": 11,
            "r": "P17",
            "t": 4
        },
        {
            "evidence": [
                0,
                2
            ],
            "h": 8,
            "r": "P17",
            "t": 4
        }
    ],
    "sents": [
        [
            "The",
            "Essingen",
            "Islands",
            "are",
            "a",
            "group",
            "of",
            "two",
            "islands",
            "—",
            "Stora",
            "Essingen",
            "and",
            "Lilla",
            "Essingen",
            "—",
            "in",
            "the",
            "Swedish",
            "lake",
            "of",
            "Mälaren",
            ",",
            "located",
            "southwest",
            "of",
            "Kungsholmen",
            "in",
            "Stockholm",
            "."
        ],
        [
            "On",
            "older",
            "maps",
            ",",
            "the",
            "islands",
            "are",
            "called",
            "Stora",
            "Hessingen",
            "and",
            "Lilla",
            "Hessingen",
            "."
        ],
        [
            "The",
            "islands",
            "were",
            "a",
            "part",
            "of",
            "the",
            "administrative",
            "Bromma",
            "Parish",
            "until",
            "1916",
            ",",
            "when",
            "they",
            "were",
            "incorporated",
            "with",
            "the",
            "parish",
            "into",
            "Stockholm",
            "Municipality",
            "."
        ],
        [
            "They",
            "remained",
            "a",
            "part",
            "of",
            "Bromma",
            "ecclesiastical",
            "parish",
            "until",
            "1955",
            ",",
            "when",
            "they",
            "received",
            "their",
            "own",
            "parish",
            "within",
            "the",
            "Church",
            "of",
            "Sweden",
            "."
        ],
        [
            "A",
            "bridge",
            "was",
            "built",
            "between",
            "the",
            "islands",
            "and",
            "Kungsholmen",
            "in",
            "1907",
            ",",
            "and",
            "between",
            "the",
            "islands",
            "themselves",
            "in",
            "1917",
            "."
        ],
        [
            "In",
            "1966",
            ",",
            "the",
            "Essingeleden",
            "motorway",
            "opened",
            "across",
            "the",
            "islands",
            "."
        ],
        [
            "The",
            "Alviksbron",
            "bridge",
            "(",
            "for",
            "pedestrians",
            ",",
            "bicycles",
            ",",
            "and",
            "trams",
            ")",
            "opened",
            "in",
            "2000",
            "."
        ]
    ],
    "title": "Essingen Islands",
    "vertexSet": [
        [
            {
                "name": "Essingen Islands",
                "pos": [
                    1,
                    3
                ],
                "sent_id": 0,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "two",
                "pos": [
                    7,
                    8
                ],
                "sent_id": 0,
                "type": "NUM"
            }
        ],
        [
            {
                "name": "Stora Essingen",
                "pos": [
                    10,
                    12
                ],
                "sent_id": 0,
                "type": "LOC"
            },
            {
                "name": "Stora Hessingen",
                "pos": [
                    8,
                    10
                ],
                "sent_id": 1,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "Lilla Essingen",
                "pos": [
                    13,
                    15
                ],
                "sent_id": 0,
                "type": "LOC"
            },
            {
                "name": "Lilla Hessingen",
                "pos": [
                    11,
                    13
                ],
                "sent_id": 1,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "Swedish",
                "pos": [
                    18,
                    19
                ],
                "sent_id": 0,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "Mälaren",
                "pos": [
                    21,
                    22
                ],
                "sent_id": 0,
                "type": "LOC"
            }
        ],
        **[
            {
                "name": "Kungsholmen",
                "pos": [
                    26,
                    27
                ],
                "sent_id": 0,
                "type": "LOC"
            },
            {
                "name": "Kungsholmen",
                "pos": [
                    8,
                    9
                ],
                "sent_id": 4,
                "type": "LOC"
            }
        ],**
        [
            {
                "name": "Stockholm",
                "pos": [
                    28,
                    29
                ],
                "sent_id": 0,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "Bromma Parish",
                "pos": [
                    8,
                    10
                ],
                "sent_id": 2,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "1916",
                "pos": [
                    11,
                    12
                ],
                "sent_id": 2,
                "type": "TIME"
            }
        ],
        [
            {
                "name": "Stockholm Municipality",
                "pos": [
                    21,
                    23
                ],
                "sent_id": 2,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "Bromma",
                "pos": [
                    5,
                    6
                ],
                "sent_id": 3,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "1955",
                "pos": [
                    9,
                    10
                ],
                "sent_id": 3,
                "type": "TIME"
            }
        ],
        [
            {
                "name": "Church of Sweden",
                "pos": [
                    19,
                    22
                ],
                "sent_id": 3,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "1907",
                "pos": [
                    10,
                    11
                ],
                "sent_id": 4,
                "type": "TIME"
            }
        ],
        [
            {
                "name": "1917",
                "pos": [
                    18,
                    19
                ],
                "sent_id": 4,
                "type": "TIME"
            }
        ],
        [
            {
                "name": "1966",
                "pos": [
                    1,
                    2
                ],
                "sent_id": 5,
                "type": "TIME"
            }
        ],
        [
            {
                "name": "Essingeleden motorway",
                "pos": [
                    4,
                    6
                ],
                "sent_id": 5,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "Alviksbron bridge",
                "pos": [
                    1,
                    3
                ],
                "sent_id": 6,
                "type": "LOC"
            }
        ],
        [
            {
                "name": "2000",
                "pos": [
                    14,
                    15
                ],
                "sent_id": 6,
                "type": "TIME"
            }
        ]
    ]
}

**Comment by vhientran** [comment]
Hi @cj555 ,

I wonder about: 'h': idx of head entity in vertexSet. What does it mean? Then, the order of elements in the list vertexSet ?
