### ISSUE TITLE
About total_recall_ignore

### ISSUE THREAD

**Issue by x-zb** [thunlp/DocRED#31]
In line713 of Config.py, when calculating ignore_F1, why do you use **total_recall** rather than **total_recall_ignore** to calculate recalls ? The variable **total_recall_ignore** seems not used in the program.
Is this correct: `pr_x.append(float(correct-correct_in_train) / total_recall_ignore)` ?

**Comment by YeDeming** [comment]
Ignore F1 is computed by the "ignore precision" and "total recall". It means the model needs to find out all facts appearing in the training set, but these facts don't affect the precision. Details are showed in:

https://github.com/thunlp/DocRED/blob/084a01ac997225b3ca3f765655e67fc86e846d22/code/evaluation.py#L141-L152

**Comment by x-zb** [comment]
Thanks for your explaination!

**Comment by seanswyi** [comment]
Hi. Can you elaborate a bit more on why you don't recalculate the ignore recall and only the precision? I'm trying to understand what you mean by "the model needs to find out all facts appearing in the training set, but these facts don't affect the precision." Thanks.
