### ISSUE TITLE
提交错误

### ISSUE THREAD

**Issue by zhongerqiandan** [thunlp/DocRED#32]
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmplppntt/run/program/evaluate.py", line 78, in 
    tmp = json.load(open(submission_answer_file))
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmplppntt/run/input/res/result.json

**Comment by YeDeming** [comment]
You should submit a zip file which contains result.json.
