### ISSUE TITLE
请问下代码里面h_mapping 和dis2idx是什么作用呢？

### ISSUE THREAD

**Issue by yangxia605** [thunlp/DocRED#36]
您好，首先，感谢您的数据集的贡献！
想请问一下代码里面h_mapping 和dis2idx是什么作用呢？
![image](https://user-images.githubusercontent.com/21167278/81049684-42f77e80-8ef1-11ea-920d-685b6bf86fa3.png)

**Comment by yangxia605** [comment]
h_t_limit=1800是什么意思呢？

**Comment by YeDeming** [comment]
h_mapping将序列位置标记头实体位置，dis2idx将距离映射到若干个桶，h_t_limit是一次处理头尾实体对的上限

**Comment by yangxia605** [comment]
好的，我明白了，非常感谢您的回答。
