### ISSUE TITLE
请问数据集在国内怎么下载

### ISSUE THREAD

**Issue by lorylee** [thunlp/DocRED#37]

**Comment by YeDeming** [comment]
你好，除了train_distant.json外在此处下载：https://cloud.tsinghua.edu.cn/d/5d8628d7f0b6453a8d7c/
https://cloud.tsinghua.edu.cn/d/99e1c0805eb64736af95/

**Comment by lorylee** [comment]
Thank you very much！ I wish you success in your work and a happy life！



在 2020-05-07 14:36:20，"YeDeming" <notifications@github.com> 写道：

你好，除了train_distant.json外在此处下载：https://cloud.tsinghua.edu.cn/d/5d8628d7f0b6453a8d7c/
https://cloud.tsinghua.edu.cn/d/99e1c0805eb64736af95/
