### ISSUE TITLE
关于vertexSet数据结构的问题。

### ISSUE THREAD

**Issue by yangxia605** [thunlp/DocRED#38]
![image](https://user-images.githubusercontent.com/21167278/82002831-76749e80-9691-11ea-9473-c9db2e39e676.png)
![image](https://user-images.githubusercontent.com/21167278/82003114-1d593a80-9692-11ea-8799-2047c95c7998.png)
![image](https://user-images.githubusercontent.com/21167278/82003173-4679cb00-9692-11ea-970f-6c4e6a883d81.png)

您好：我想请问一下这个Set数组里面的数据，为什么数组里面还要嵌套一层呢？里面不是按照句子id分组，也不是按照实体类型分组。这么混合组合是表示什么呢？后面的labels里面有h和t表示的是外层数据集的index的位置，那h和t组成的关系是一个vertexSet数组外层元素里面嵌套数组所有实体之间都存在这种关系吗？
万分感谢！！

**Comment by YeDeming** [comment]
你好，一个实体(entity)拥有多个出现的位置(mention)

**Comment by yangxia605** [comment]
好的，明白了。谢谢您的回答。
