### ISSUE TITLE
Generating data

### ISSUE THREAD

**Issue by ghomasHudson** [thunlp/DocRED#39]
Do you have the scripts for generating data directly from Wikipedia and Wikidata?

Would be great to see exactly how you processed the data and extend your approach.

**Comment by YeDeming** [comment]
We use https://github.com/attardi/wikiextractor to process https://dumps.wikimedia.org/. I am sorry that we lose our original code

**Comment by ghomasHudson** [comment]
In your paper, you mention:

>"We link each named entity mention to one Wikidata item by a heuristic-based method, which jointly considers the frequency of a target Wikidata item and its relevance to the current document"

What exactly was the heuristic you used?

**Comment by YeDeming** [comment]
There are anchor text in wikipedia, which includes a hyperlink to wikidata item. The title of the article is also corresponding to a wikidata item. We refers them as a set S.

The frequency of a target Wikidata item:  counting the item's hyperlink frequency in Wikipedia

The relevance to the current document. We adopt 2~3 step BFS search to find the surrounding items of S, through Wikidata's  'Statements'  relational edge.
