### ISSUE TITLE
head and tail are not given in test set

### ISSUE THREAD

**Issue by cj555** [thunlp/DocRED#4]
Hi, 
For a relation extraction task, will the head and tail be given in the test？ 

Thanks

**Comment by YeDeming** [comment]
Hi,

The label of test set is hidden, you can test on https://competitions.codalab.org/competitions/23392

Deming Ye

**Comment by cj555** [comment]
Hi, Deming.

I mean, in normal relation extraction task, head and tail are given and the model only needs to predict relation. (head, tail, ?)

It seems that DocRed needs to predict the triple (?, ?, ?). Am I right? 

Thanks,
Best,
CJ

**Comment by YeDeming** [comment]
Yes, in real-word setting, we don't know which is potential head and tail entity.

**Comment by cj555** [comment]
Cool. Thanks for the reply.
