### ISSUE TITLE
Test set labels

### ISSUE THREAD

**Issue by crystal-xu** [thunlp/DocRED#40]
Hi,

I am not sure if I have missed anything here. But it seems that the test set, i.e. "test.json" does not have any labels? I am a bit confused now. Am I supposed to split the testing set out by myself?

Thanks

**Comment by crystal-xu** [comment]
> Hi,
> 
> I am not sure if I have missed anything here. But it seems that the test set, i.e. "test.json" does not have any labels? I am a bit confused now. Am I supposed to split the testing set out by myself?
> 
> Thanks

I think I know how to do evaluation now. I have submitted my result to CodaLab. But it seems that the automatic evaluation result in CodaLab doesn't include AUC, right? Is there any way that I could get AUC for the testing set just as what you have presented in your DocRED paper?

Thank you very much!

**Comment by YeDeming** [comment]
You can send me your result (ydm18@mails.tsinghua.edu.cn). The relational facts should be sorted according to their probability (high->low)

**Comment by crystal-xu** [comment]
> You can send me your result ([ydm18@mails.tsinghua.edu.cn](mailto:ydm18@mails.tsinghua.edu.cn)). All the relational facts(e.g. (entity1, entity2, x), x should be enumerated in 96relations except NA ) should be sorted according to their probability (high->low)

Great! I really appreciate your help.
