### ISSUE TITLE
python3 evaluation.py result.json ../data/dev.json

### ISSUE THREAD

**Issue by qiunlp** [thunlp/DocRED#41]
Hi：
当我运行 python3 evaluation.py result.json ../data/dev.json
出错  result.json/res doesn't exist
怎么处理呢？
谢谢！

**Comment by deepaca** [comment]
Hi,

Would you please tell how to resolve this issue? 
When I run python3 evaluation.py result.json ../data/dev.json I got the same result. 
What to do?

Thank you!
