### ISSUE TITLE
关于数据集实体关系同一句子和跨句子的问题

### ISSUE THREAD

**Issue by yangxia605** [thunlp/DocRED#43]
您好：
请问下数据集中labels的evisence是表示两个实体间的关系是位于同一句子或跨句子吗？如下图所示：
![image](https://user-images.githubusercontent.com/21167278/86073123-bc58bb00-bab5-11ea-8c52-465db9375cd6.png)
感谢！！！

**Comment by yaoyuanTHU** [comment]
您好，如果只有一个证据语句一般是单句关系。如果有多个证据语句则无法确定，因为可能其中每个句子都能单独证明该关系，需要结合具体情况分析。

**Comment by yangxia605** [comment]
好的，感谢你。
