### ISSUE TITLE
关于h_mapping * context_output 问题的请教

### ISSUE THREAD

**Issue by VinnyHu** [thunlp/DocRED#44]
非常感谢您出色的工作
我想请问下 用 h_mapping * context_output 是由什么意义吗？
还有就是h_mapping与t_mapping的计算方式不是很理解
h_mapping[i, j, h['pos'][0]:h['pos'][1]] = 1.0 / len(hlist) / (h['pos'][1] - h['pos'][0])
这样计算的目的在于什么呢，通过之前您在issue中的回答，我没有看懂，谢谢！

**Comment by YeDeming** [comment]
一个实体有多个mention，mention表示为其内单词的平均，实体的表示为mention表示的平均，h_mapping从整个序列的表示中得到实体的表示

**Comment by VinnyHu** [comment]
谢谢您！
