### ISSUE TITLE
label问题

### ISSUE THREAD

**Issue by VinnyHu** [thunlp/DocRED#45]
还想再请问一下您，relation_multi_lable、relation_label、relation_mask他们的作用分别是什么？有什么不同吗？
谢谢您！

**Comment by YeDeming** [comment]
这是一个多标签分类问题，所以两个实体间有若干关系，relation_mask表示是否有关系，relation_multi_label为sigmoid预测关系的标签，relation_label保留了一个关系用于粗略统计当前结果

**Comment by VinnyHu** [comment]
好的，谢谢您了！非常感谢！

**Comment by VinnyHu** [comment]
> 这是一个多标签分类问题，所以两个实体间有若干关系，relation_mask表示是否有关系，relation_multi_label为sigmoid预测关系的标签，relation_label保留了一个关系用于粗略统计当前结果

您好，我想再问下，您计算标注训练集的时候，计算资源怎么样？我按照您的设定2块2080，batch_size设定成了32，大概运行七八十个epoch之后会被kill掉。

**Comment by YeDeming** [comment]
把plt.plot注释掉应该就不会被kill掉了，这个比较耗内存

**Comment by VinnyHu** [comment]
> 把plt.plot注释掉应该就不会被kill掉了，这个比较耗内存

好的，谢谢，我去试一下
