### ISSUE TITLE
Questions about Theta

### ISSUE THREAD

**Issue by ssppff** [thunlp/DocRED#48]
Hello, thank you for sharing. What does Theta stand for in training? When I was doing my experiments, Theta was always high, up to 0.9, and I didn't change the Theta part of the code. How do you keep Theta stable during training? Thank you.

**Comment by YeDeming** [comment]
We automaticly select the best theta for highest F1 in development set. And apply it to the test set. It didn't need to be stable.

**Comment by ssppff** [comment]
Thank you very much for your answer, but I can't find out what Theta stands for?

**Comment by YeDeming** [comment]
if the predict probability < theta, we regard the prediction "non-relation"
