### ISSUE TITLE
coreference resolution in distantly supervised data

### ISSUE THREAD

**Issue by baozi-lala** [thunlp/DocRED#49]
How does the data set constructed by distantly supervised supervision do coreference resolution.

**Comment by yaoyuanTHU** [comment]
We first conduct entity linking to link the entity mentions to Wikidata items. Entity mentions with identical KB IDs are considered to be from the same entity and are automatically merged into groups to provide coreference recommendation for human annotators. We will reopen the issue if you have any further questions.

**Comment by baozi-lala** [comment]
Are there human annotators for automatically aligned data using distantly supervision method?

**Comment by yaoyuanTHU** [comment]
No. The distantly supervised data is automatically collected without human annotators.

**Comment by baozi-lala** [comment]
Does it have coreference resolution?  And how to do this process without human annotators?
