### ISSUE TITLE
about the relation type?

### ISSUE THREAD

**Issue by samaritan1998** [thunlp/DocRED#50]
关于论文中提到的  the relation types are organized in a well defined hierarchy and taxonomy?请问一下有关系分类的文件么

**Comment by yaoyuanTHU** [comment]
关系的类别可以在Wikidata的页面中找到[link](https://www.wikidata.org/wiki/Wikidata:List_of_properties), 具体的taxonomy需要从Wikidata dump中的instance of和sub-class of对应的三元组中抽取

**Comment by WatsonWangZh** [comment]
> 关系的类别可以在Wikidata的页面中找到[[link]](https://www.wikidata.org/wiki/Wikidata:List_of_properties), 具体的taxonomy需要从Wikidata dump中的instance of和sub-class of对应的三元组中抽取。如果有问题的话我们随时再open这个issue

请问可以提供关系的层级分类数据吗？自己在对应三元组中抽取的话，怕丧失公平性
