### ISSUE TITLE
AUC score

### ISSUE THREAD

**Issue by xiaoyuxin1002** [thunlp/DocRED#51]
Hi, may I ask how exactly did you compute the AUC score for the development set?
I think the code in Config.py is a bit unclear. Could you please explain the procedure a bit more? Thanks!

**Comment by yaoyuanTHU** [comment]
Suppose we have n entity pairs in total and m positive relations, then we will have m x n relation scores in total (Note that NA scores are ignored). We rank these scores, and calculate the precision-recall curve, and finally compute the area under curve. A similar implementation could also be found in OpenNRE https://github.com/thunlp/OpenNRE.

**Comment by yaoyuanTHU** [comment]
We will reopen the issue if you have any further questions.

**Comment by xiaoyuxin1002** [comment]
May I ask if you calculate the AUC score for each document separately and compute the average in the end or if you compute the AUC score for all the documents together?

**Comment by Zoher15** [comment]
@xiaoyuxin1002 do you know how the auc is calculated?
