### ISSUE TITLE
What is the purpose of the code block (lines 77-94) in `gen_data.py`?

### ISSUE THREAD

**Issue by seanswyi** [thunlp/DocRED#52]
I'm trying to understand what it does, but there are no cases where `is_training == True` and therefore all of the values for the keys `'intrain'` and `'indev_train'` for `new_labels` is going to be `False`.

What is the point of this block of code?

**Comment by YeDeming** [comment]
Hi, these two flags is used to compute the ignore F1 in the paper.

'intrain' means ignoring triples in distant training set for computing precision in IgnF1
'indev_train' means ignoring triples in annoated training set for computing precision in IgnF1

**Comment by seanswyi** [comment]
Correct me if I'm wrong, but this block of code never runs and seems redundant. I was curious if I was running things incorrectly or if the block of code is indeed redundant.

**Comment by YeDeming** [comment]
is_training==True when we handle the distant training datasaet:

https://github.com/thunlp/DocRED/blob/64622e608d06e83deda6b6e0e871effb9d1fd74c/code/gen_data.py#L189
