### ISSUE TITLE
char2id.json, char_vec.npy, vec.npy, word2id.json是如何得到的

### ISSUE THREAD

**Issue by Caiji-123** [thunlp/DocRED#53]
请问char2id.json, char_vec.npy, vec.npy, word2id.json是怎么拿到的，其他的文档级数据集能否同样适用这些数据？或者该怎么自己预训练？在什么语料上面训练？

**Comment by YeDeming** [comment]
你好，词向量是下载的glove vector，char向量随机初始化的向量
