### ISSUE TITLE
如何选择合适的测试集input_theta？

### ISSUE THREAD

**Issue by IKeepMoving** [thunlp/DocRED#55]
你好，因为测试集没有label，所以不能计算best_f1，那么如何确定测试集合适的input_theta或者w呢？默认-1，我得到的result.json有3.47GB

**Comment by Caiji-123** [comment]
我也遇到了这个问题，请问你解决了吗？是不是用train的时候最好的那个theta代替？

**Comment by IKeepMoving** [comment]
> 我也遇到了这个问题，请问你解决了吗？是不是用train的时候最好的那个theta代替？

是的

**Comment by jinxin19970504** [comment]
请问最后你是怎么计算得到w的？

**Comment by jinxin19970504** [comment]
测试集没有labels，无法得到best_f1，请问你的w是怎么计算得到的？
