### ISSUE TITLE
Non-tokenized sentences

### ISSUE THREAD

**Issue by alexeyev** [thunlp/DocRED#56]
Dear colleagues,
thank you for the great effort and a cool dataset!

May I ask you if it is possible to download the raw (non-tokenized) sentences?

Thank you!

**Comment by yaoyuanTHU** [comment]
Hi, Alexeyev. I'm afraid that the raw sentences cannot be found now on our server. Nevertheless, you can download the Wikipedia dump and use the article title to get the corresponding raw text.

**Comment by alexeyev** [comment]
Hi @yaoyuanTHU.  Thank you for the response.
