### ISSUE TITLE
如何使用自己的数据集

### ISSUE THREAD

**Issue by feiba54** [thunlp/DocRED#58]
您好！我希望能在您的代码下使用自己构建的数据集训练模型，数据集已规整为train_annotated.json文件的格式，请问应该如何替换呢？prepro_data文件夹下新生成的dev_train.json似乎才是训练时真正使用到的数据集，但是"na_triple"和"Ls"含义不明，生成的若干.npy文件是否与数据集相关？如果不相关，可否直接替换dev_train.json？谢谢。

**Comment by YeDeming** [comment]
你好，几个npy文件，跟数据集无关，是glove词向量太大，过滤了一下只留下出现过的词形成npy。 Ls是句子累积长度(for sent id)，na_triple是负例样本，认为没标注到的都是负例
