### ISSUE TITLE
Supporting Evidence

### ISSUE THREAD

**Issue by nayakt** [thunlp/DocRED#6]
Hi,

In your paper in Table 7, the Neural Predictor is trained separately or it is trained together with models in Table 4?

Regards
Tapas

**Comment by YeDeming** [comment]
Hi  nayakt,
The Neural Predictor is trained separately.  Input triples predicted by a RE model and output the supporting evidence for each.

**Comment by VinnyHu** [comment]
> Hi nayakt,
> The Neural Predictor is trained separately. Input triples predicted by a RE model and output the supporting evidence for each.

你好，能不能详细说明下，在Neural Predictor中目标函数的设置，还有网络结构？原文中的几句话看的不是太明白。谢谢了！

**Comment by YeDeming** [comment]
你好，结构是BiLSTM之后拿句子开头结尾的embeding拼起来作0/1分类

**Comment by VinnyHu** [comment]
> 你好，结构是BiLSTM之后拿句子开头结尾的embeding拼起来作0/1分类

非常感谢您的回答！那网络是和RE model用multi-task的方式做的嘛？就像HotPotQA里面的结构？RE model预测三元组，然后Neural Predictor 对每个sentence做0/1分类？

**Comment by YeDeming** [comment]
对的就是借鉴了HotpotQA的代码，但不是multi-task而两个分别训练，预测的时候是先预测三元组再预测sentence 0/1

**Comment by VinnyHu** [comment]
> 对的就是借鉴了HotpotQA的代码，但不是multi-task而两个分别训练，预测的时候是先预测三元组再预测sentence 0/1

我刚开始以为您是用HotPotQA那种思路，下层的encoder是共享的，那么目前，您是分别训练2两个model嘛？也可以说Neural Predictor的model其实跟RE model没什么关系，是分来训练的？RE 的base model例如用BiLSTM做encoder，然后分类。Neural Predictor的model也是用像BiLSTM做encoder，然后二分类。他们之间的encoder都是分别训练的？
谢谢！

**Comment by YeDeming** [comment]
目前是分别训练的

**Comment by VinnyHu** [comment]
> 目前是分别训练的

谢谢！感谢您的耐心回复！

**Comment by VinnyHu** [comment]
> 目前是分别训练的

您好，Neural Predictor 的代码能否开源分享下？十分感谢！！
