### ISSUE TITLE
about statistics of dev.json

### ISSUE THREAD

**Issue by ridiculouz** [thunlp/DocRED#62]
Hello,
I download the data from the Google Drive link, and I find that there are only 998 passages in dev.json, which differs from 1000 reported in the paper. Does there exist some problems in the latest data?

**Comment by ady-yu** [comment]
> Hello, I download the data from the Google Drive link, and I find that there are only 998 passages in dev.json, which differs from 1000 reported in the paper. Does there exist some problems in the latest data?

Do you know why? I have the same question.

**Comment by lijp12** [comment]
Hello,
Do you know why there is the difference?

**Comment by ridiculouz** [comment]
Hi,
The author removed 2 samples in dev.json due to duplication. See https://github.com/thunlp/DocRED/issues/59.
