### ISSUE TITLE
how to convert prediction result tensor back to relation text

### ISSUE THREAD

**Issue by doofin** [thunlp/DocRED#63]
Thanks for this awesome NRE repo ! I see some relevant code in Config.py : 
```python                            
r = np.argmax(predict_re[i, j])
if (h_idx, t_idx, r) in label:
  top1_acc += 1
```

Does `h_idx, t_idx ` mean the start and end index of the word in document and `r` means the tensor for relation type ? How to convert them back to text document ? Thanks !

**Comment by yaoyuanTHU** [comment]
Hi, `h_idx, t_idx` are the index of the head and tail entity in the `VertexSet`, and `r` is the relation type index. Each entity in the`VertexSet` has the corresponding textual names, which can be used for the conversion.
