### ISSUE TITLE
How to apply a trained model to predict relations on a given text?

### ISSUE THREAD

**Issue by fillipefbr** [thunlp/DocRED#64]
Hello,

I trained a BiLSTM model following the documentation and now I wish to use this model to predict relations for arbitrary texts.

How can I achieve this? 

Thanks in advance.

**Comment by yaoyuanTHU** [comment]
Hi, to predict relations for arbitrary texts, you will need to pre-process your text following the same format as our provided validation set.

**Comment by maherr13** [comment]
Hello, 

May you provide the code for inference on arbitrary text? 

Many thanks

**Comment by heimaozidew** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件，我会尽快给您回复的
