### ISSUE TITLE
Invalid file type (application/json).

### ISSUE THREAD

**Issue by FDUyjx** [thunlp/DocRED#65]
你好，请问一下，现在CodaLab上提交测试集的预测结果result.json为何却显示Invalid file type (application/json)？是现在入口暂时关闭了吗？我该如何得到在测试集上的结果呢？

**Comment by yaoyuanTHU** [comment]
你好，评测提交文件需要是zip格式的，而不是json格式的。评测系统目前是正常的。

**Comment by heimaozidew** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件，我会尽快给您回复的
