### ISSUE TITLE
Does the dev.json file misses two examples?

### ISSUE THREAD

**Issue by yu-xiang-wang** [thunlp/DocRED#68]
i have downloaded the data from url [https://drive.google.com/drive/folders/1c5-0YwnoJx8NS6CV2f-NoTHR__BdkNqw](url) and use the following code to read data:
`len(json.load(open("dev.json")))`
and i get 998 as the result, which is different from 1000 (the number reported in the paper).
ps.
i have notice that in google drive the dev.json was last modified in August 2021, does the modification remove something?

**Comment by heimaozidew** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件，我会尽快给您回复的

**Comment by yaoyuanTHU** [comment]
Hi, we found that the there are duplicate articles between dev and test set in our initial released version. To make minimal influence on the existing results on the dataset, we remove the two duplicated articles from the dev set.
