### ISSUE TITLE
Possibility of partial test set evaluation?

### ISSUE THREAD

**Issue by davidleejy** [thunlp/DocRED#69]
Hello, is it possible to do a partial test set evaluation (for example, test on randomly selected 50% or 75% of samples in the test set)?

Thanks for the dataset and advice!

**Comment by heimaozidew** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件，我会尽快给您回复的

**Comment by yaoyuanTHU** [comment]
Hi, thanks for contacting! The evaluation results on test set can be obtained from our [CodaLab competition](https://codalab.lisn.upsaclay.fr/competitions/365#learn_the_details-overview), which supports 5 maximum submissions per day. Models can also be evaluated on the validation set, which follows the same distribution of test set. These should be sufficient to evaluate the models.

**Comment by heimaozidew** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件，我会尽快给您回复的
