### ISSUE TITLE
AUC Calculation

### ISSUE THREAD

**Issue by Zoher15** [thunlp/DocRED#72]
Hi,

Similar to issue #51, I have a clarification question. @yaoyuanTHU said 

> "n entity pairs in total and m positive relations, then we will have m x n relation scores in total (Note that NA scores are ignored)"

For example, if there are 100 entities in dev set, then total entity pairs are 4950 (100 choose 2). If total relations in dev set are 100, does that mean the score is calculated over 4950*100=4,95,000 triples?

**Comment by heimaozidew** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已经收到您的邮件，我会尽快给您回复的

**Comment by Zoher15** [comment]
@zibuyu @yaoyuanTHU @Mrlyk423 @YeDeming @MaosongSun @THUCSTHanxu13 Anyone that can help explain?

**Comment by yaoyuanTHU** [comment]
Thanks for your interest. During evaluation, we do not know which entity pairs have positive relations in advance. Therefore, we need to perform relation classification for all entity pairs, without any sampling. In your case, for a document containing 100 entities, we need to score 4,95,000 triples. Hope this is helpful for your work.
