### ISSUE TITLE
Leaderboard Move Request.

### ISSUE THREAD

**Issue by WatsonWangZh** [thunlp/DocRED#73]
Will you move the leaderboard at https://competitions.codalab.org/competitions/20717#results to https://codalab.lisn.upsaclay.fr/?

**Comment by yaoyuanTHU** [comment]
Thanks for the reminder. We will move the leaderboard soon.

**Comment by yaoyuanTHU** [comment]
Hi, the leaderboard is moved to the new server (https://codalab.lisn.upsaclay.fr/competitions/365)
