### ISSUE TITLE
codalab issue

### ISSUE THREAD

**Issue by nayakt** [thunlp/DocRED#8]
Getting following error while trying to submit result in codalab:

Failed, competition phase is being migrated, please try again in a few minutes

Regards
Tapas

**Comment by YeDeming** [comment]
codalab down recently, please wait.

**Comment by ewrfcas** [comment]
@YeDeming It seems that codalab's database is damaged. The new address is https://competitions-new.codalab.org, but i can't find this competition.

**Comment by nayakt** [comment]
May be they have not migrated your competition to the new site yet. Anyway thanks !!!!

**Comment by YeDeming** [comment]
[CodaLab of DocRED](https://competitions-new.codalab.org/competitions/20147) is reinstated now
