### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by DesireHope** [thunlp/DocRED#9]
当我运行的时候出现如下错误，请问如何解决？
CUDA_VISIBLE_DEVICES=0 python3 train.py --model_name BiLSTM --save_name checkpoint_BiLSTM --train_prefix dev_train --test_prefix dev_dev
===============================================
Reading training data...
train dev_train
Finish reading
Reading testing data...
dev_dev
Finish reading
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    con.train(model[args.model_name], args.save_name)
  File "/home/deep/daipeng/DocRED/code/config/Config.py", line 468, in train
    for data in self.get_train_batch():
  File "/home/deep/daipeng/DocRED/code/config/Config.py", line 268, in get_train_batch
    relation_multi_label[i, j, r] = 1
TypeError: new(): invalid data type 'str'

**Comment by YeDeming** [comment]
试一下python3?

**Comment by DesireHope** [comment]
就python3


发自我的iPhone

------------------ Original ------------------

**Comment by YeDeming** [comment]
感谢你的反馈，rel2id.json的目标键值应该是数字而不是字符串，已在[TsinghuaCloud](https://cloud.tsinghua.edu.cn/d/99e1c0805eb64736af95/)中更新
